version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data  
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
        - .:/rails
        ports:
        - "3000:3000"
        depends_on:
        - db
        - redis
        environment:
        - DATABASE_URL=postgresql://postgres:password@db:5432/your_cart_development
        - REDIS_URL=redis://redis:6379/0
        - RAILS_ENV=development
        - BUNDLE_WITHOUT=test
        - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    test:
        build: .
        command: bundle exec rspec
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis 
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/your_cart_test
            - REDIS_URL=redis://redis:6379/0
volumes:
    postgres13:
    redis_data: